# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Cookie-Pack
version:      0.13
version_from: Pack.pm
installdirs:  site
requires:
    CGI::UriThingy:                0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
